# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    defaults:
      run:
        working-directory: fit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache-dependency-path: go.sum
    - name: Install dependencies
      run: |
        go get -v
    
    - name: Build For Linux
      run: GOOS=linux go build -v
      
    - name: Build For Windows
      run: GOOS=windows go build -v
    
    - name: Upload linux binary
      uses: actions/upload-artifact@v3
      with:
        name: fit
        path: ./
    
    - name: Upload windows binary
      uses: actions/upload-artifact@v3
      with:
        name: fit.exe
        path: ./
      
